[package]
name = "imgui-sdl2-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgui = "0.11.0"
imgui-sys = "0.11.0"
sdl2-bindings = { path = "./src/bindings" }
